### ISSUE TITLE
Conflicting Editions

### ISSUE THREAD

**Issue by laniroe** [digiah/sobf#1]
Hyperlink to page containing explanations of all differences between the different editions

Complete by Feb. 10

**Comment by rcrath** [comment]
see notes in [moodle wiki](http://www.way.net/rrath/mod/wiki/view.php?id=5) and [google doc](https://docs.google.com/document/d/1ve_y67Ef0FJInFNwDr79c1tQsS-QJ2gG8mNDV8DEET0/edit#heading=h.nmrh3okgmj3j), and [Oxford ed. of SOBF](https://marxistnkrumaistforum.files.wordpress.com/2013/12/du-bois-the-souls-of-black-folk-oxford-worlds-classics.pdf), p xxv

**Comment by rcrath** [comment]
RC Rath, [Dubois's Afrocentric Pragmatism](http://way.net/rcr/Rath_EchoAndNarcissus.pdf)

**Comment by rcrath** [comment]
the moodle wiki page is [here](http://dahi.manoa.hawaii.edu/tmp/SOBFWiki.html) or for hon 491, [here](http://www.way.net/rrath/mod/wiki/view.php?id=214). the key thing we need to deal with for this issue is p xxv of oxford ed. above.
