### ISSUE TITLE
indoctrinate new members

### ISSUE THREAD

**Issue by rcrath** [digiah/sobf#11]
@JoelleByars @alysiamb @EVolosci These are issues. Look through them and see if you can address any of them.  If you can, you then close the issue.  If you run into a new problem, you create a new issue.

[Here](http://www.way.net/rrath/course/view.php?id=9) is the Moodle Du Bois site as a demonstration of markup.  Also you can refer to other issues by using the hashtag as in #10.

**Comment by JoelleByars** [comment]
Here is my comment #11

**Comment by alysiamb** [comment]
My comment.

**Comment by EVolosci** [comment]
Liz
