### ISSUE TITLE
Chapter 1 image blurry

### ISSUE THREAD

**Issue by rcrath** [digiah/sobf#20]
The image for chapter 1 is from an old version.  need to delete that image and import "02 Nobody Knows.png" from [SoBF materials](http://dahi.manoa.hawaii.edu/sobf/images/staging/), then insert the image into the page.  See [chapter two](http://dahi.manoa.hawaii.edu/scalar2/the-souls-of-black-folk/chapter-two-of-the-dawn-of-freedom?path=index) for what it should look like.

**Comment by JoelleByars** [comment]
I updated the media file and have now uploaded the Nobody Knows local file and matched the formatting so the picture should no longer be blurry
