### ISSUE TITLE
Proofreading master list

### ISSUE THREAD

**Issue by rcrath** [digiah/sobf#22]
When each of these is done for a chapter, check off the chapter.
- [local media import](http://scalar.usc.edu/works/guide2/importing-your-own-media) the correct image from [additional materials-images-staging](http://dahi.manoa.hawaii.edu/sobf/images/staging/) with the correct format for the title and description.  See the [image page for Chapter 12's music](http://dahi.manoa.hawaii.edu/scalar2/the-souls-of-black-folk/media/swing-low-sweet-chariot.edit) for an example to model.
- proofread the chapter and format it properly, removing any parts that are not in the [Oxford Edition](https://marxistnkrumaistforum.files.wordpress.com/2013/12/du-bois-the-souls-of-black-folk-oxford-worlds-classics.pdf).  If the parts are another student's previous work, paste it in to the [google doc](https://docs.google.com/document/d/1OHGuXNxMYhtAC9BxPV7k2HJDR-MyP6xt13le_HWBJYw/edit#) under the appropriate heading.  If it is a link and the link goes to an actual essay or resource, put the link in the google doc. we will go over all this later.  For now, you want your text to match the Oxford Edition word for word, and as close as you can get in looks.  Keep any asterisks, as we may turn them into hyperlinks later. The only exception is "immigrant" as discussed in issue #1. Especially look for missing text and words that are glommed together with a missing space likethis.  

- [x] The Forethought
- [x] I. Of Our Spiritual Strivings
- [x] II. Of the Dawn of Freedom
- [x] III. Of Booker T. Washington and Others
- [x] IV. Of the Meaning of Progress
- [x] V. Of the Wings of Atalanta
- [x] VI. Of the Training of Black Men
- [x] VII. Of the Black Belt
- [x] VIII. Of the Quest of the Golden Fleece
- [x] IX. Of the Sons of Master and Man
- [x] X. Of the Faith of the Fathers
- [x] XI. Of The Passing of the First-Born
- [x] XII. Of Alexander Crummell
- [x] XIII. Of the Coming of John
- [x] XIV. Of the Sorrow Songs
- [x] The Afterthought

**Comment by JoelleByars** [comment]
All media files are updated and formatted correctly, the only issues remaining are proofreading against Oxford Edition

@rcrath @alysiamb @EVolosci
