### ISSUE TITLE
innerhtml on home page js problem

### ISSUE THREAD

**Issue by rcrath** [digiah/sobf#23]
Hi @digiah/dev I need help as I have exhausted my nonexistent .js skills.  On the [Du Bois home page](http://dahi.manoa.hawaii.edu/scalar2/the-souls-of-black-folk/index), It says "Contents" above the path.  I want it to say "Herein is Written" as it does in the hard copy.  I tried inserting the following into the "add javascript" section at the bottom of the edit page under the styling tab:

```
document.getElementById("h1").innerHTML = "Herein is Written";
```

I think it is the right code but the wrong string in the first quoted part ("h1"), but it produces the header on the fly as part of the function to create a path (the actual table of contents).

Help?  If you add javascript to the page itself it seems to crash the page.  You have to backspace the browser to get back into an edit screen if that happens.

**Comment by damg70** [comment]
“H1” is a tag type, not a css identifier so that JavaScript won’t work. 

Unless you can assign an ID attribute to the H1 tag you can’t “reach” its innerHTML with that call. 

If you’re putting that JS into the scalar page’s JS field you also can’t just have that call “naked” by itself because we don’t know what order scalar renders JavaScript. This is probably why the page crashes. 

:david

I'm all thumbs over here

**Comment by rcrath** [comment]
I tried a temp ID tag on it in the dev frame css named "#test" with the innerhtml named "test" and "#test" too.  that did not work either.  It seems the script runs before the html that the  innerhtml produces is loaded, since the heading is put in there by the path function on the fly. The script turns up "id not found" either way.  Then the separate question is where to permanently assign the id tag for the path header.  I need to rewrite the h1 tag to contain the id in order for the script to run it seems, but the script is what writes the tag.  aaaarg.   I'll try on the scalar list.

**Comment by rcrath** [comment]
Have a [query in at anvc](https://github.com/anvc/scalar/issues/85)

**Comment by rcrath** [comment]
@damg70 , @craigdietrich came through with the solution.  I was way off.
