### ISSUE TITLE
media files in scalar2 are still from scalar1

### ISSUE THREAD

**Issue by rcrath** [digiah/sobf#4]
All the media files are still located in the old broken scalar one. we need to re-import them to scalar 2 and fix the media library and all the stuff that is linked to the items in it. go to scalar2 dashboard for SOBF and pick media tab to see.

**Comment by damg70** [comment]
1. I copied all the files from the old media folder to the new one
2. the scalar2 URL is “the-souls-of-black-folk” while the scalar1 URL is “souls-of-black-folk”
3. all of the links are hard-coded to the latter url.
4. in order of labor from least to most is: 
a. can leave it be
b. change the name of the scalar2 book’s base URL, removing “the-“… 
c. download and re-upload all of the media… side note: some things are still pointing to way.net <http://way.net/>

please advise.

**Comment by rcrath** [comment]
we will go the hard way on this.  I'll break it out into a couple of issues and @kelseykato  can take it on.  the files need to be made regular, both in format and naming.  Then we need a storage area outside of scalar I think.  anyway, look for the individual issues.

**Comment by rcrath** [comment]
I'll close this in the meanwhile.
